### ISSUE TITLE
git v2.37 interactive --patch: error: could not parse colored hunk header

### ISSUE THREAD

**Issue by OJFord** [so-fancy/diff-so-fancy#437] opened 2022-06-28 15:04 UTC
I haven't had a chance to look much into this, but this seemed to start with git v2.37.0:

```shell
$git init
$git config interactive.diffFilter 'diff-so-fancy --patch'
$touch empty
$git add empty
$echo not > empty
$git add -p empty
error: could not parse colored hunk header '?[1;35m?[1;35m@ empty:1 @?[1m?[0m'
```

**Comment by scottchiefbaker** [comment] 2022-06-28 15:18
I don't have git v.2.37.0 installed so I'm flying blind here... The phrase "could not parse" is not in d-s-f anywhere, so I'm sort of confused. What is generating that error? Git itself?

My first guess would be that it's some new ANSI color sequence we just don't understand yet. Can you generate a "raw" file and recreate the problem?

**Comment by scottchiefbaker** [comment] 2022-06-28 15:49
Hmmmmmm that looks like a pretty vanilla diff ANSI color sequence to me. Maybe Git made some changes that look for a VERY specific sequence?

**Comment by OJFord** [comment] 2022-06-28 16:02
May be a git _bug_ of course. Delta facing the same issue: dandavison/delta/issues/1114

Some recent changes (new in 2.37) https://github.com/git/git/commits/master/add-patch.c, 

> "git add -p" rewritten in C regressed hunk splitting in some cases,

sounds, err, maybe related.. but I can't actually find what 'rewritten in C' refers to, `add-patch.c` seems to have been there years.

**Comment by scottchiefbaker** [comment] 2022-06-28 16:03
Oh nice... Good find!

**Comment by malsyned** [comment] 2022-06-28 19:42
This work-around worked for me:
```git config --global add.interactive.useBuiltin false```
Obviously that's not ideal long-term since it disables the new faster `git add -p` implementation.

**Comment by malsyned** [comment] 2022-06-28 20:05
> sounds, err, maybe related.. but I can't actually find what 'rewritten in C' refers to, `add-patch.c` seems to have been there years.

The configuration flag `add.interactive.useBuiltin` got a new default value of `true` in 2.37. The implementation has existed for a while but has been considered experimental and disabled by default until now.

**Comment by OJFord** [comment] 2022-06-28 20:41
Thanks!

**Comment by phil-blain** [comment] 2022-07-06 12:51
I would say it is a Git regression, and should be reported to the Git mailing list: http://git-scm.com/community.

**Comment by shmup** [comment] 2022-07-20 16:29
> This work-around worked for me: `git config --global add.interactive.useBuiltin false` Obviously that's not ideal long-term since it disables the new faster `git add -p` implementation.

Hm, enabling that presents me with:

```
$ git add -p

fatal: mismatched output from interactive.diffFilter
hint: Your filter must maintain a one-to-one correspondence
hint: between its input and output lines.
```

Specifically setting:

```
[add "interactive"]
	useBuiltin = false
[interactive]
	diffFilter = diff-so-fancy --patch
```

**Comment by albandiguer** [comment] 2022-07-28 09:40
The solution from Malsyned also works with nix & home manager. 
```
programs.git = {
  extraConfig = {
    add.interactive.useBuiltin = false;
  }
}
```

**Comment by phil-blain** [comment] 2022-08-22 22:18
> I would say it is a Git regression, and should be reported to the Git mailing list: http://git-scm.com/community.

Reported here: https://lore.kernel.org/git/ecf6f5be-22ca-299f-a8f1-bda38e5ca246@gmail.com/T/#u

**Comment by phil-blain** [comment] 2022-10-03 19:18
Fixed in Git 2.38 which came out today: https://github.com/git/git/blob/3dcec76d9df911ed8321007b1d197c1a206dc164/Documentation/RelNotes/2.38.0.txt#L353-L356

**Comment by scottchiefbaker** [comment] 2022-10-03 19:31
@phil-blain good catch!

**Comment by will** [comment] 2022-10-03 19:32
@phil-blain thanks for taking the time to post here, this is great news!

**Closed** 2022-10-03 23:05 UTC
