### ISSUE TITLE
Brew formula not found

### ISSUE THREAD

**Issue by alanrsoares** [so-fancy/diff-so-fancy#78] opened 2016-02-17 01:58 UTC
```
$ brew install diff-so-fancy
```
```
Error: No available formula for diff-so-fancy
Searching formulae...
Searching taps...
```

```
$ brew search diff-so-fancy
```
```
No formula found for "diff-so-fancy".
Searching pull requests...
Closed pull requests:
diff-so-fancy 0.4.0 (https://github.com/Homebrew/homebrew/pull/49222)
diff-so-fancy 0.3.0 (new formula) (https://github.com/Homebrew/homebrew/pull/49040)
```

**Comment by stevemao** [comment] 2016-02-17 02:17
duplicate of https://github.com/so-fancy/diff-so-fancy/issues/71

**Closed by stevemao** 2016-02-17 02:17 UTC
