### ISSUE TITLE
Background color breaks +/- sign stripping

### ISSUE THREAD

**Issue by maxnordlund** [so-fancy/diff-so-fancy#204] opened 2016-11-10 16:07 UTC
When using background colors the +/- signs in the beginning of the lines aren't stripped anymore. But on lines that don't have it they still do.

My config:
```ini
[color "diff"]
	old = yellow
	new = yellow bold
[color "diff-highlight"]
	oldNormal = 196 88
	oldHighlight = 196 bold 88
	newNormal = 231 22
	newHighlight = 231 30
```

![skarmavbild 2016-11-10 kl 17 05 43](https://cloud.githubusercontent.com/assets/664779/20184153/fe7f5512-a767-11e6-9f31-b40edf43beb9.png)

**Comment by stevemao** [comment] 2016-11-18 05:57
Are you on the latest version? If you use a different color the `+/-` signs will be stripped?

**Comment by maxnordlund** [comment] 2016-11-18 11:02
I've installed it using `brew`, which reports version 0.11.2. I assume this is the latest? It's not a three way merge, just the stuff I've ben working on.
I'll tried a few a different colors, but I'll try some more. It's only affected by background color though.

**Comment by OJFord** [comment] 2017-01-13 20:10
I can't reproduce this, works for me. Have you checked a different terminal emulator?

**Comment by stevemao** [comment] 2017-01-18 22:09
@maxnordlund Is there a simple way to reproduce the issue? You could try using [report-bug.sh](https://github.com/so-fancy/diff-so-fancy#reporting-bugs)

**Comment by maxnordlund** [comment] 2017-01-18 22:36
OK, so I've played around a bit more and the steps to reproduce are:

1. Use the config in the description
2. `git diff HEAD..HEAD^`

<details>
 <summary>Using the report-bug script gives:</summary>
Z2l0IGRpZmYgSEVBRC4uSEVBRF4KZGlmZiAtLWdpdCBhL3JlYWRtZS5tZCBiL3JlYWRtZS5tZAppbmRleCBiZGFlMWJkLi4yZTQ2YTVhIDEwMDY0NAotLS0gYS9yZWFkbWUubWQKKysrIGIvcmVhZG1lLm1kCkBAIC05MSw3ICs5MSw3IEBAIFNob3VsZCB0aGUgcGVza3kgYCtgIG9yIGAtYCBhdCBsaW5lLXN0YXJ0IGJlIHJlbW92ZWQuCiAKICMjIyB1c2VVbmljb2RlUnVsZXIKIAotQnkgZGVmYXVsdCB0aGUgc2VwYXJhdG9yIGZvciB0aGUgZmlsZSBoZWFkZXIgdXNlcyBVbmljb2RlIGxpbmUgZHJhd2luZyBjaGFyYWN0ZXJzLiAgCitCeSBkZWZhdWx0IHRoZSBzZXBhcmF0b3IgZm9yIHRoZSBmaWxlIGhlYWRlciB1c2VzIHVuaWNvZGUgbGluZSBkcmF3aW5nIGNoYXJhY3RlcnMuICAKIElmIHRoaXMgaXMgY2F1c2luZyBvdXRwdXQgZXJyb3JzIG9uIHlvdXIgdGVybWluYWwgc2V0IHRoaXMgdG8gYGZhbHNlYCB0byB1c2UgQVNDSUkgY2hhcmFjdGVycyBpbnN0ZWFkLgogCiBCeSBkZWZhdWx0IGFsbCB0aGUgY29uZmlncyBhcmUgdHJ1ZS4gWW91IGNhbiB0dXJuIGFueSBvZmYgYnkgcnVubmluZzoKCgoKZ2l0IGRpZmYgSEVBRC4uSEVBRF4gLS1jb2xvcgobWzFtZGlmZiAtLWdpdCBhL3JlYWRtZS5tZCBiL3JlYWRtZS5tZBtbbQobWzFtaW5kZXggYmRhZTFiZC4uMmU0NmE1YSAxMDA2NDQbW20KG1sxbS0tLSBhL3JlYWRtZS5tZBtbbQobWzFtKysrIGIvcmVhZG1lLm1kG1ttChtbMzZtQEAgLTkxLDcgKzkxLDcgQEAbW20gG1ttU2hvdWxkIHRoZSBwZXNreSBgK2Agb3IgYC1gIGF0IGxpbmUtc3RhcnQgYmUgcmVtb3ZlZC4bW20KIBtbbQogIyMjIHVzZVVuaWNvZGVSdWxlchtbbQogG1ttChtbMzNtLUJ5IGRlZmF1bHQgdGhlIHNlcGFyYXRvciBmb3IgdGhlIGZpbGUgaGVhZGVyIHVzZXMgVW5pY29kZSBsaW5lIGRyYXdpbmcgY2hhcmFjdGVycy4gIBtbbQobWzE7MzNtKxtbbRtbMTszM21CeSBkZWZhdWx0IHRoZSBzZXBhcmF0b3IgZm9yIHRoZSBmaWxlIGhlYWRlciB1c2VzIHVuaWNvZGUgbGluZSBkcmF3aW5nIGNoYXJhY3RlcnMuG1ttG1s0MW0gIBtbbQogSWYgdGhpcyBpcyBjYXVzaW5nIG91dHB1dCBlcnJvcnMgb24geW91ciB0ZXJtaW5hbCBzZXQgdGhpcyB0byBgZmFsc2VgIHRvIHVzZSBBU0NJSSBjaGFyYWN0ZXJzIGluc3RlYWQuG1ttCiAbW20KIEJ5IGRlZmF1bHQgYWxsIHRoZSBjb25maWdzIGFyZSB0cnVlLiBZb3UgY2FuIHR1cm4gYW55IG9mZiBieSBydW5uaW5nOhtbbQpnaXQgY29uZmlnIHBhZ2VyLmRpZmYKZGlmZi1zby1mYW5jeSB8IGxlc3MgLVJGWCAtLXRhYnM9NCAtLXBhdHRlcm49J14oYWRkZWR8ZGVsZXRlZHxtb2RpZmllZCk6ICcKZ2l0IGNvbmZpZyBwYWdlci5zaG93Cg==
</details>

![Screenshot](https://cloud.githubusercontent.com/assets/664779/22085737/a852ca62-ddd5-11e6-9697-e6439a860b19.png)

The issue is that the `+`/`-` signs aren't stripped when using numbers as the background color values in the config, so using a config like:

```ini
[color "diff"]
	old = 124
	new = 33
[color "diff-highlight"]
	oldNormal = 124
	oldHighlight = 160
	newNormal = 33
	newHighlight = 39
```

Looks like this:

![Screenshot](https://cloud.githubusercontent.com/assets/664779/22085895/69dbe5d8-ddd6-11e6-8f0d-7c891c351ef8.png)

However using the script does something weird which gives this output instead:

![Screenshot](https://cloud.githubusercontent.com/assets/664779/22085937/a9d616a4-ddd6-11e6-9d45-bee95dafef4e.png)

When I first dug into this the culprit seemed to be using numbers for color values and background colors, but frankly I've no idea why it behaves so strangely.

**Comment by scottchiefbaker** [comment] 2017-01-19 02:38
I'm not sure I'm totally tracking what you're describing here. Are you saying when you use numbers as the background (oldHighlight and newHighlight) it doesn't strip out the `+` or `-` ?

I used the exact color config you specified above, and then ran `git diff HEAD..HEAD^` in the diff-so-fancy repo and I'm seeing that the `+` and `-` **are** stripped. 

You said:

> However using the script does something weird 

but I'm not clear on exactly what you meant. You *may* be on to something with the background color thing, as that's a different ANSI color sequence that perhaps we're not catching. I'm just unable to recreate it. 

Also can you indicate what platform you're on? What OS? What version of Perl? What shell are you using, etc.

**Comment by scottchiefbaker** [comment] 2017-07-10 15:29
Any updates on this?

**Comment by scottchiefbaker** [comment] 2017-11-03 17:32
There havn't been any updates on this in over ten months. I'm going to close this since we can't recreate it. If this is still and issue let me know and I'll reopen it.

**Closed by scottchiefbaker** 2017-11-03 17:32 UTC
