### ISSUE TITLE
Clean `a/` and `b/` prefix on header

### ISSUE THREAD

**Issue by Spy-Seth** [so-fancy/diff-so-fancy#79] opened 2016-02-17 10:29 UTC
Hi,

I want to suggest you an improvement: removing the prefix `a/` or `b/` in the header. It will make the file path easier to select. 

<img width="320" alt="screenshot 2016-02-17 11 28 48" src="https://cloud.githubusercontent.com/assets/95120/13106626/a2153bf0-d569-11e5-8fd9-5d873cd3b3af.png">

**Comment by stevemao** [comment] 2016-02-17 10:36
Duplicate of #28

**Closed by stevemao** 2016-02-17 10:36 UTC
