### ISSUE TITLE
Use of uninitialized value $value in substitution (s///) at /usr/local/bin/diff-so-fancy line 370

### ISSUE THREAD

**Issue by jdsutherland** [so-fancy/diff-so-fancy#243] opened 2017-07-15 02:04 UTC
I'm getting the following error for any `git diff` operation after updating to 1.1.0 release via homebrew:

`Use of uninitialized value $value in substitution (s///) at /usr/local/bin/diff-so-fancy line 370`

[diff.txt](https://github.com/so-fancy/diff-so-fancy/files/1149992/diff.txt)

**Comment by scottchiefbaker** [comment] 2017-07-16 14:30
Uhhhh line 370 is parsing your gitconfig. That's super weird! Can you post your gitconfig?

**Comment by jdsutherland** [comment] 2017-07-16 17:37
@scottchiefbaker [.gitconfig](https://gist.github.com/eb9883954cca761acb85f6c2d6e462d1)

**Comment by bertocq** [comment] 2017-07-17 18:32
I'm having the same problem. By trial and error I figured out the gitconfig that was causing the problem was:
```
[merge "railsschema"]
  name = newer Rails schema version
  driver = "ruby -e '\n\
          system %(git), %(merge-file), %(--marker-size=%L), %(%A), %(%O), %(%B)\n\
          b = File.read(%(%A))\n\
          b.sub!(/^<+ .*\\nActiveRecord::Schema\\.define.:version => (\\d+). do\\n=+\\nActiveRecord::Schema\\.define.:version => (\\d+). do\\n>+ .*/) do\n\
            %(ActiveRecord::Schema.define(:version => #{[$1, $2].max}) do)\n\
          end\n\
          File.open(%(%A), %(w)) {|f| f.write(b)}\n\
          exit 1 if b.include?(%(<)*%L)'"
```

Not a custom thing, I've seen it on other places, I think origin is http://tbaggery.com/2010/10/24/reduce-your-rails-schema-conflicts.html

**Comment by scottchiefbaker** [comment] 2017-07-17 18:39
Oh good catch... My git config parsing stuff expects `key = value` and in this case you've got a multiline thing with no `=` in it. I believe I already addressed this in 3224f531412fd605cfca7b328daeb9b1a5fb2218, can you try using the `next` branch and see if this fixes it for you?

**Comment by bertocq** [comment] 2017-07-17 19:18
I'm sorry @scottchiefbaker but not sure how to do that :( I've installed this using homebrew, and I can't find a way to upgrade it manually >_<

**Comment by OJFord** [comment] 2017-07-17 19:20
@bertocq `brew install --HEAD` will install from the git repo; I believe there's options for selecting a branch too. (I'm not on a mac at the moment, `brew install --help` should tell you.)

**Comment by DanielThomas** [comment] 2017-07-17 19:41
Also can be caused by this kind of thing:

```
dad = "!curl -w '\n' https://icanhazdadjoke.com"
```

**Comment by scottchiefbaker** [comment] 2017-07-17 20:05
@bertocq try this "[binary](https://www.perturb.org/tmp/diff-so-fancy)" which includes the fix.

**Comment by r-richmond** [comment] 2017-07-17 22:25
ran into this issue as well... and just fyi
```
brew install --HEAD diff-so-fancy
Error: No head is defined for diff-so-fancy
```

**Comment by bertocq** [comment] 2017-07-17 23:14
👏  @scottchiefbaker worked for me :) 

PS: I couldn't get brew to install from repo as well :( I did some research but found no working response.

**Comment by OJFord** [comment] 2017-07-18 18:44
Huh, sorry @r-richmond, that must be missing from the brew formula. I'll see about adding that for future, it can be pretty handy. (And doesn't require trusting ~~dodgy~~ binaries. :wink:)

**Comment by scottchiefbaker** [comment] 2017-07-18 20:35
I'm 99% sure this is fixed on `next`. If things are quiet for the next couple of days I'll release a 1.1.1 to fix this and a couple other minor issues.

**Closed by scottchiefbaker** 2017-07-18 20:35 UTC
