### ISSUE TITLE
Merge diffs formatted poorly

### ISSUE THREAD

**Issue by heftig** [so-fancy/diff-so-fancy#81] opened 2016-02-17 21:29 UTC
Removal of the initial +/- interacts poorly with merge diffs, which have two initial columns of indicators.

I also suspect octopus merges can have even more.

**Comment by noscript** [comment] 2016-02-17 22:12
What do you propose?

**Comment by heftig** [comment] 2016-02-17 22:17
I am in favor of returning to the normal indicators (#69) for now.

**Comment by noscript** [comment] 2016-02-17 22:20
Considering this a duplicate of #69.

**Closed by noscript** 2016-02-17 22:20 UTC
