### ISSUE TITLE
Can't use string ("auto") as a HASH ref while "strict refs" in use at /usr/local/bin/diff-so-fancy line 376.

### ISSUE THREAD

**Issue by SimenB** [so-fancy/diff-so-fancy#245] opened 2017-07-15 07:37 UTC
When I try to use the colors you've defined in your readme, I get the title as an error.

This is using 1.1.0.

`[color "diff-highlight"]` are ok, but not `[color "diff"]`.

Full git config https://github.com/SimenB/vcsh_git/blob/2f94f33d90261c4690c557bbecc9901d1b00edb3/.gitconfig

**Comment by SimenB** [comment] 2017-07-15 07:46
Ok, figured it out. It was because I had `[color] diff = auto`. Not sure if it should be considered a bug? Maybe print a better message.

https://github.com/SimenB/vcsh_git/blob/2f94f33d90261c4690c557bbecc9901d1b00edb3/.gitconfig#L35

As an aside, I don't think the colors you suggest in the readme are better than `auto`.

Auto:
![image](https://user-images.githubusercontent.com/1404810/28237545-4401821c-6942-11e7-89ee-d2384fcf417d.png)

Colors in readme:
![image](https://user-images.githubusercontent.com/1404810/28237547-4c2d8bf2-6942-11e7-9767-c021a132a38b.png)

**Comment by scottchiefbaker** [comment] 2017-07-16 14:31
I didn't even know color "auto" was a thing. I'll take a look at this and let you know when I find the fix.

**Comment by OJFord** [comment] 2017-07-16 14:52
FWIW, it's the default, (rename your `git/config` and run `git config --list`) so should probably be fixed.

Regarding colour preference though, I believe (though I can't find a reference) that `auto` uses some default assignments of `red`, `green`, whatever; which in turn use the colours for those ANSI codes as defined in your terminal configuration. In general, that probably is what you want; if you want to go blue/yellow rather than red/green for example, using `blue`, `yellow` instead of specific codes will ensure it picks up your terminal colour scheme, leaving you with just a single place to ensure the colours are legible in their various combinations, and on your background.

I think the colours suggested in the readme are more an 'FYI, these are what were used for the screenshots'.

**Comment by SimenB** [comment] 2017-07-16 15:00
>The default colors are not the best so we recommend the following color settings as a base.

Maybe it could also suggest to try "auto"?

Is it possible to get rename highlight to work with `auto`?

**Comment by scottchiefbaker** [comment] 2017-07-17 15:40
rename hightlight is handled by DiffHighlight so it uses the d-h colors:

    [color "diff-highlight"]
        oldNormal = red bold
        oldHighlight = red bold 52
        newNormal = green bold
        newHighlight = green bold 22

**Comment by scottchiefbaker** [comment] 2017-07-17 15:42
For what it's worth your colors/terminal seems off compared to mine. What terminal are you using?

Konsole on Linux:
![ss](https://user-images.githubusercontent.com/3429760/28276469-e15bf684-6acb-11e7-8419-26a85e622a5d.png)

**Comment by scottchiefbaker** [comment] 2017-07-17 15:50
Circling back... I set the color to `auto` like you specified and I do **not** get the error you specified. 

    [color]
        branch = auto
        diff = auto
        status = auto
        ui = auto

Perhaps there is something else in your config that's triggering this? I'd like to recreate it so I can attempt to work around it.

**Comment by Leglaw** [comment] 2017-07-17 16:56
I'm able to reproduce with this minimal config:
```
[color]
	diff = auto
[color "diff"]
	meta = 227
[pager]
	diff = diff-so-fancy | less --tabs=4 -RFX
	show = diff-so-fancy | less --tabs=4 -RFX
```
If `[color "diff"]` appears before `[color]` it doesn't produce the issue. Also, it doesn't matter what rule appears in `[color "diff"]`, just that any rule is specified.

**Comment by SimenB** [comment] 2017-07-18 06:38
iTerm2 on mac with DimmedMonokai theme.

(tried to find the same commit, seems like I missed :P)
![image](https://user-images.githubusercontent.com/1404810/28303607-59152b46-6b94-11e7-9803-049e056fa457.png)

**Comment by scottchiefbaker** [comment] 2017-07-18 14:52
That looks closer for sure. I'm guessing it's your theme that's skewing the colors a little bit. Not a big deal, I was just curious why they weren't mapping 1:1.

**Comment by scottchiefbaker** [comment] 2017-07-18 14:54
@Leglaw and @SimenB This should be fixed on the [beta](https://www.perturb.org/tmp/diff-so-fancy) version I released yesterday. Can you test and confirm for me?

**Comment by Leglaw** [comment] 2017-07-18 15:26
👍  Works for me

**Comment by lancespeelmon** [comment] 2017-07-18 16:50
FYI - same problem here... changing the order in `~/.gitconfig` fixed it though.

**Comment by scottchiefbaker** [comment] 2017-07-18 20:37
I'm 99% sure this is fixed on `next`. If things are quite for a couple days I'll release a 1.1.1 to fix this.

**Closed by scottchiefbaker** 2017-07-18 20:37 UTC
