### ISSUE TITLE
Horizontal line separating files steps up

### ISSUE THREAD

**Issue by dadgar** [so-fancy/diff-so-fancy#80] opened 2016-02-17 18:08 UTC
Hey this is on a Mac running in either iTerm or built in terminal

<img width="1920" alt="screen shot 2016-02-17 at 10 06 46 am" src="https://cloud.githubusercontent.com/assets/1047914/13119510/537ad12c-d55e-11e5-83e5-860724cff027.png">

**Comment by dcalhoun** [comment] 2016-02-17 19:48
I am also experiencing this issue on Mac OS X 10.11.3 (15D21) and iTerm 2.1.4. Installed diff-so-fancy via npm.

**Comment by noscript** [comment] 2016-02-17 22:10
Duplicate of #72

**Closed by noscript** 2016-02-17 22:10 UTC

**Comment by pauley-unsaturated** [comment] 2016-02-17 22:33
@dcalhoun Can you reproduce this with TOT diff-so-fancy?  We believe the original of your issue was fixed yesterday, so it's important to know if this is related to npm or if it just didn't get fixed for everybody.

**Comment by paulirish** [comment] 2016-02-18 00:24
Hey guys, this is a bug that snuck in but was fixed in 0.4.1.

`npm install -g diff-so-fancy` will get you to 0.4.1, or a manual install.

**Comment by dcalhoun** [comment] 2016-02-18 13:59
Yes, upgrading to 0.4.1 resolved this issue for me.
