### ISSUE TITLE
diff-so-fancy should support standard diff. 

### ISSUE THREAD

**Issue by joedaniels29** [so-fancy/diff-so-fancy#273] opened 2017-10-19 21:01 UTC
Would be nice if I could pipe /usr/bin/diff to diff-so-fancy. 

Seems to not work correctly, ant least with the version I have.

**Comment by scottchiefbaker** [comment] 2017-10-19 21:02
I'm closing this because it's a dupe of #220. It's a long term goal to get there, but there are issues with making sure the input is consistent between the two formats. Git does some massaging of the data that d-s-f relies on currently.

**Closed by scottchiefbaker** 2017-10-19 21:02 UTC

**Comment by joedaniels29** [comment] 2017-11-19 21:28
well thanks for hearing this out! I know I would appreciate it!
