### ISSUE TITLE
Unable to detect new line and modified old

### ISSUE THREAD

**Issue by boris-petrov** [so-fancy/diff-so-fancy#331] opened 2019-05-14 07:10 UTC
This is the `diff.txt` output from the [bug report procedure](https://github.com/so-fancy/diff-so-fancy/blob/master/reporting-bugs.md):

```
git diff HEAD..HEAD^
diff --git a/a.txt b/a.txt
index 7123d55..198b8f8 100644
--- a/a.txt
+++ b/a.txt
@@ -1,2 +1 @@
-// some added line
-x = 2;
+x = 1;



git diff HEAD..HEAD^ --color
[1;33mdiff --git a/a.txt b/a.txt[m
[1;33mindex 7123d55..198b8f8 100644[m
[1;33m--- a/a.txt[m
[1;33m+++ b/a.txt[m
[1;35m@@ -1,2 +1 @@[m
[1;31m-// some added line[m
[1;31m-x = 2;[m
[1;32m+[m[1;32mx = 1;[m
git config pager.diff
diff-so-fancy | less --tabs=4 -RFX
git config pager.show
diff-so-fancy | less --tabs=4 -RFX
```

The idea is:

1) I add a commit with one line:

```
x = 1;
```

2) Modify the file:

```
// some added line
x = 2;
```

3) Diffing shows that one line was removed and 2 were added - but actually only one was added and the other was modified.

`--word-diff=color` works fine. Why doesn't `diff-so-fancy` use that? I see it will also fix #329.

**Comment by scottchiefbaker** [comment] 2019-05-14 20:21
This is an interesting problem. The underlying issue is the raw diff output.

	-x = 1;
	+// some added line
	+x = 2;

In the raw diff from `git` (and also from `diff -u`) the comment line is between the two `x` lines. This means there is no way for `diff-highlight` to treat the lines as a modification. Perhaps @peff has some insight as to the guts of `diff-highlight` that might help?

**Comment by scottchiefbaker** [comment] 2019-05-14 20:25
Interestingly... all three of these diff fragments output the **exact** same d-s-f output when run like: `cat foo.patch | diff-so-fancy`. Perhaps I don't understand how `diff-highlight` works as well as I thought.

```
diff --git a/test b/test
index 198b8f8..7123d55 100644
--- a/test
+++ b/test
@@ -1 +1,2 @@
-x = 1;
+// some added line
+x = 2;
```

```
diff --git a/test b/test
index 198b8f8..7123d55 100644
--- a/test
+++ b/test
@@ -1 +1,2 @@
+// some added line
-x = 1;
+x = 2;
```

```
diff --git a/test b/test
index 198b8f8..7123d55 100644
--- a/test
+++ b/test
@@ -1 +1,2 @@
+// some added line
+x = 2;
-x = 1;
```

**Comment by peff** [comment] 2019-05-15 17:00
This is the expected behavior from diff-highlight. It doesn't do a full word-level diff over each hunk, but rather matches lines based on position, and then looks for a common prefix/suffix on matched lines. There are some cases that look better with this strategy, and some that look worse. One of the nice things is that it does not have to have content-specific regexes to tokenize the words to get good results, like word-diff does (just try reading the [builtin regexes](https://github.com/git/git/blob/ef7435264c3ac91b4cbebd52385a1c532f12bb2d/userdiff.c#L16) sometime).

There's some discussion in the "Bugs" section of the [README](https://github.com/git/git/blob/ef7435264c3ac91b4cbebd52385a1c532f12bb2d/contrib/diff-highlight/README#L132). And in [this thread](https://public-inbox.org/git/1434388853-23915-1-git-send-email-patrick@parcs.ath.cx/) from the mailing list; especially further down in the thread there are some experiments with a true LCS diff.

Your case might also be helped by the line-matching attempt discussed [here](https://public-inbox.org/git/1446516334-27652-1-git-send-email-jonathan.lebon@gmail.com/). We never ended up applying that series because it had such a big performance impact (but it might be salvageable by skipping the matching for big hunks).

In the long run I'd really like to see this kind of highlighting pushed into Git's internal diff. It already has the word-diff tokenizers. But as discussed in that first thread, there are some real complications around the way whitespace munging already modifies the buffer internally. So I think we'd need a fair bit of refactoring in the diff code.

I don't think anybody has immediate plans to work on any of this. But hopefully if somebody does, this will give them a bit of a roadmap. Or at the very least some background reading.

**Comment by scottchiefbaker** [comment] 2019-05-15 17:12
Thanks @peff, great write-up!

Since this is the desired output from `diff-highlight` I'm going to close the issue. If this is something you're really passionate about you'll need to address it upstream.

**Closed by scottchiefbaker** 2019-05-15 17:12 UTC
