### ISSUE TITLE
Whitespace deletions on empty lines don’t get highlighted correctly

### ISSUE THREAD

**Issue by fbruetting** [so-fancy/diff-so-fancy#480] opened 2024-01-22 11:34 UTC
I’m using the latest Git master version of DSF (f4fc36a).

In my screenshot down below you see the diff after just deleting EOL-whitespace. While lines which also contain non-whitespace content get shown correctly in the diff, the upper three and the last changes are whitespace deletions on otherwise empty lines, which instead show up like an additional line got added. The lines above the green insert symbols don’t show the deleted tab.

![Bildschirmfoto vom 2024-01-22 12-23-45](https://github.com/so-fancy/diff-so-fancy/assets/10520767/e85ca5d1-441a-4d78-b298-680316614211)

Here you see that deleted lines which contain whitespace don’t show up as deleted at all:
![Bildschirmfoto vom 2024-01-22 12-47-33](https://github.com/so-fancy/diff-so-fancy/assets/10520767/537b4654-8376-4493-8fb0-910c62cee2c8)

**Comment by OJFord** [comment] 2024-01-22 17:19
Thanks - but duplicate of #385, closing just to keep focus there.

**Closed as not planned by OJFord** 2024-01-22 17:19 UTC
