### ISSUE TITLE
Horizontal rules not displaying correctly.

### ISSUE THREAD

**Issue by davidteren** [so-fancy/diff-so-fancy#72] opened 2016-02-16 16:38 UTC
Please see the image. I'm using the Solarized Dark xterm-256color theme from https://github.com/mathiasbynens/dotfiles

![diff-so-fancy](https://cloud.githubusercontent.com/assets/5962867/13083151/7426a98c-d4dc-11e5-9d73-204449fa2c36.png)

**Comment by noscript** [comment] 2016-02-16 16:43
Apparently backslash in `\n` doesn't need to be escaped. Please try to patch `diff-so-fancy`:
```diff
-    | $SED -E "s/^($color_code_regex)\-\-\-(.*)$/\1$(print_horizontal_rule)\\n\1\-\-\-\5/g" \
-    | $SED -E "s/^($color_code_regex)\+\+\+(.*)$/\1\+\+\+\5\\n\1$(print_horizontal_rule)/g"
+    | $SED -E "s/^($color_code_regex)\-\-\-(.*)$/\1$(print_horizontal_rule)\n\1\-\-\-\5/g" \
+    | $SED -E "s/^($color_code_regex)\+\+\+(.*)$/\1\+\+\+\5\n\1$(print_horizontal_rule)/g"
```

**Comment by davidteren** [comment] 2016-02-16 17:00
Tried and same effects.

![diff-so-fancy2](https://cloud.githubusercontent.com/assets/5962867/13083875/87b8efca-d4df-11e5-8635-56bbbab73916.png)

**Comment by noscript** [comment] 2016-02-16 17:15
Would you please try `\\\n`?

**Comment by paulirish** [comment] 2016-02-16 18:06
with this:

```
    | $SED -E "s/^($color_code_regex)\-\-\-(.*)$/\1$(print_horizontal_rule)\\\n\1\-\-\-\5/g" \
    | $SED -E "s/^($color_code_regex)\+\+\+(.*)$/\1\+\+\+\5\\\n\1$(print_horizontal_rule)/g"
```

I see 
![image](https://cloud.githubusercontent.com/assets/39191/13085818/f4259032-d494-11e5-917f-cf8b44a00fbf.png)

**Comment by paulirish** [comment] 2016-02-16 18:08
Relevant: http://stackoverflow.com/questions/1421478/how-do-i-use-a-new-line-replacement-in-a-bsd-sed

**Comment by pauley-unsaturated** [comment] 2016-02-16 18:46
This might be related to my stuff (in that it allows using bsd sed instead of gnu-sed).  It looks like the recommended way to do this is to use ANSI-C quoting:
NL=$'\n' and then replace \n with ${NL} or something like that.

The strange thing is that it "works on my machine".

**Comment by paulirish** [comment] 2016-02-16 20:02
@pauley-unsaturated yah i'm positive it's your stuff. :) Now it's clear why I had done those lame newlines originally.

I'm on el capitan if that's any different. 

can you give me a snippet with the ansi-c quoting to try out?

**Comment by stevemao** [comment] 2016-02-16 22:59
Can you guys try #75?

**Comment by jlipps** [comment] 2016-02-16 23:06
@stevemao for me that turns the faint-colored `n` into a `\1`, so not much of an improvement. i'm on mac 10.10, i think also using the solarized dark term theme.

**Comment by pauley-unsaturated** [comment] 2016-02-16 23:18
Please try this:
@@ -26,6 +26,7 @@ else
 fi
 
 CSI=$'\x1b\['
 NL=$'\n'
...
   # simplify the unified patch diff header
   $SED -E "s/^($color_code_regex)diff --git .*$//g" \
     | $SED -E "/$git_index_line_pattern/{N;s/$git_index_line_pattern\n//;}" \
     | $SED -E "s/^($color_code_regex)\-\-\-(.*)$/\1$(print_horizontal_rule)\\${NL}\1\-\-\-\5/g" \
     | $SED -E "s/^($color_code_regex)\+\+\+(.*)$/\1\+\+\+\5\\${NL}\1$(print_horizontal_rule)/g"
 }
 
 colorize_context_line () {

**Comment by pauley-unsaturated** [comment] 2016-02-16 23:19
Also: I think this had something to do with the merge.  I can post a PR with this change if you like.

**Comment by pauley-unsaturated** [comment] 2016-02-16 23:26
Weird: my new changes eat a + / - ... in the file-name header.

**Comment by stevemao** [comment] 2016-02-16 23:26
@pauley-unsaturated Yes please.

**Comment by elyscape** [comment] 2016-02-17 00:11
@jlipps Interesting. I'm on 10.11 and don't have that issue. Maybe they changed sed between 10.10 and 10.11.

**Comment by davidteren** [comment] 2016-02-17 04:05
Installing a GNU sed version via Homebrew solves the issue.
`brew install gnu-sed --with-default-names`

**Comment by elyscape** [comment] 2016-02-17 04:24
It shouldn't be necessary to install GNU sed to deal with this, though.

**Comment by Treri** [comment] 2016-02-17 06:10
same problem.

**Comment by zackhsi** [comment] 2016-02-17 06:31
+1

**Comment by pauley-unsaturated** [comment] 2016-02-17 06:38
Okay, there seems to be a bit of confusion here: my patch works for me (#77).  I'm on 10.11 and using the built in BSD sed. @jlipps seems to suggest that this won't work for some other users.  @zackhsi, @Treri, @davidteren: does #77 not fix your issue?  If so, please say so on that PR.  If not, please post your config: bsd / gnu sed, OS / version, etc.

**Comment by davidteren** [comment] 2016-02-17 07:48
@pauley-unsaturated you are correct. Confusion abounds :)
I removed the gnu-sed I'd brewed, did `git pr 77` to pull the fix & it's all good now. https://github.com/so-fancy/diff-so-fancy/pull/77 fixes the issue.

**Comment by jlipps** [comment] 2016-02-17 22:01
`npm install`ed latest release and this issue is also resolved for me. thanks!

**Comment by stevemao** [comment] 2016-02-17 22:22
This issue still exists in the latest version?

**Comment by noscript** [comment] 2016-02-17 22:29
According to #80 it does. Two complains since the release. I wonder how do the tests with OSX env pass in Travis.

**Comment by pauley-unsaturated** [comment] 2016-02-17 22:31
I don't know if I believe they have the right bits yet.  #77 doesn't even have an 'n' character in the NL sequence, which is what they're seeing pop up on their screen.

**Comment by paulirish** [comment] 2016-02-18 00:09
I'm 90% sure our friends on #80 don't have 0.4.1

We can close this one. Thanks @pauley-unsaturated and all.

**Closed by paulirish** 2016-02-18 00:09 UTC
Labels: bug

**Comment by williamboman** [comment] 2016-05-13 16:40
I'm having this issue on Ubuntu 14.04.4 LTS
![screenshot 2016-05-13 at 18 36 24](https://cloud.githubusercontent.com/assets/6705160/15254957/a20e12c6-1939-11e6-8716-ddafe38538b2.png)

**Comment by scottchiefbaker** [comment] 2016-05-13 16:55
@williamboman what terminal is that? I'm guessing the terminal isn't properly handling the long dash `\xe2\x94\x80`. Have you tried another terminal?

**Comment by williamboman** [comment] 2016-05-13 16:58
> @williamboman what terminal is that?

iTerm2.

![screenshot 2016-05-13 at 18 57 27](https://cloud.githubusercontent.com/assets/6705160/15255488/9181af8c-193c-11e6-9c39-c6feb862db45.png)

**Comment by scottchiefbaker** [comment] 2016-05-13 16:59
Try changing line 50 of `diff-so-fancy` to just

```
local -r dash=$( printf "-" )
```

**Comment by williamboman** [comment] 2016-05-13 17:01
<img width="900" alt="screenshot 2016-05-13 at 19 00 38" src="https://cloud.githubusercontent.com/assets/6705160/15255572/01b77a48-193d-11e6-8f83-24e8906eb2ab.png">

**Comment by scottchiefbaker** [comment] 2016-05-13 17:03
If your terminal handles that correctly try changing that line to:

```
local -r dash=$( printf \\xe2\\x94\\x80 )
```

**Comment by williamboman** [comment] 2016-05-13 17:06
Hm, same issue as before.

**Comment by scottchiefbaker** [comment] 2016-05-13 17:37
The old version of this file had that function as one line:

```
print_horizontal_rule () {
  printf "%$(tput cols)s\n"| $SED 's/ /─/g'
}
```

Try that?

**Comment by williamboman** [comment] 2016-05-13 17:49
Still same as before. The issue exists on all "minor" versions. I'll be happy just monkey-patching it to use `-` instead though (feel free to ask questions if you wanna debug it though). Thanks!

**Comment by scottchiefbaker** [comment] 2016-05-13 17:51
You're using iTerm2? 

http://iterm2.com/

On Ubuntu? I can't test with this. @paulirish runs diff-so-fancy on OSX, maybe he has feedback? I only have Linux.

**Comment by williamboman** [comment] 2016-05-13 17:52
Using iTerm2 to ssh into an Ubuntu server.

**Comment by stevemao** [comment] 2016-05-13 22:19
I use iTerm2 2.1.4 on OSX 10.11.4 with the latest dsf, no problem

@williamboman maybe worth it to post the versions?

**Comment by williamboman** [comment] 2016-05-13 22:53
iTerm2 Build 2.9.20160510
Ubuntu 14.04.4 LTS
sed (GNU sed) 4.2.2
diff-so-fancy@0.9.1
perl v5.18.2
bash 4.3.11(1)

**Comment by scottchiefbaker** [comment] 2016-05-14 00:14
Is it a font thing? What font-face are you using @williamboman?

**Comment by scottchiefbaker** [comment] 2016-05-16 20:19
I had to completely rework the horizontal-rule code for something unrelated. I'm curious if that work will fix this issue as well. Can you try out this branch:

https://github.com/scottchiefbaker/diff-so-fancy/tree/binary-file-header

The original code uses the ['BOX DRAWINGS LIGHT HORIZONTAL'](http://www.fileformat.info/info/unicode/char/2500/index.htm) character to draw that line. I thought it was an em-dash, but I was wrong. That may be part of the problem?

After this re-work I think we're much closer to a solution.

**Comment by williamboman** [comment] 2016-05-16 22:11
Nope :/

![](http://i.imgur.com/QG4r0RN.png)

**Comment by scottchiefbaker** [comment] 2016-05-16 22:33
If you uncomment line 369 and comment out line 371 (i.e. use em-dash instead of box-drawings), does it work?

**Comment by williamboman** [comment] 2016-05-16 22:37
Nope
![screenshot 2016-05-17 at 00 36 42](https://cloud.githubusercontent.com/assets/6705160/15306026/7315ad86-1bc7-11e6-857e-1e215461d053.png)

**Comment by scottchiefbaker** [comment] 2016-05-16 22:38
Man that is some funky unicode weirdness you've got going on there. I don't know what else it could be, and I can't test iTerm2 very easily :(

**Comment by williamboman** [comment] 2016-05-16 22:42
I can repro with Terminal.app, iTerm2.app, [Chrome Secure Shell App](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo?hl=en) and stock Ubuntu Trusty terminal.

**Comment by scottchiefbaker** [comment] 2016-05-16 22:43
What font-face are you using? I wonder if that font doesn't have those particular code points?

**Comment by williamboman** [comment] 2016-05-16 22:49
Setting `LC_CTYPE=en_US.UTF-8` fixed it.

**Comment by scottchiefbaker** [comment] 2016-05-16 22:50
What was it before?

**Comment by williamboman** [comment] 2016-05-16 22:52
It was unset

**Comment by scottchiefbaker** [comment] 2016-05-16 22:53
Excellent... well it's good to know that was the fix. I'm pondering if that's something we shouldn't check for at run time? Or at least in our tests?

**Comment by williamboman** [comment] 2016-05-16 22:53
Actually, it stops working inside a tmux session 😅

**Comment by elyscape** [comment] 2016-05-17 00:04
@williamboman, in the Terminal.app settings, under Advanced, what does it say for Text Encoding? That is to say, here:

![Terminal.app settings](https://cloud.githubusercontent.com/assets/792695/15307469/1f6cb254-1b88-11e6-867d-fc2976bc2c2c.png)

Also, what's the value of `$LANG` in your shell?

**Comment by williamboman** [comment] 2016-05-17 00:53
It's not a terminal issue per se. I've been experimenting a bit and it turns out the issue is with `less(1)` and unset `LC_{CTYPE,ALL}`, `LANG`, `LESSCHARSET` variables. Everyone can repro by

```sh
unset LC_CTYPE LC_ALL LANG LESSCHARSET
git show # unicode hex codes in angle brackets
git --no-pager show | diff-so-fancy # works cause no pipe to less(1)
```
