### ISSUE TITLE
^M displayed in some line edits for files with CRLF line endings

### ISSUE THREAD

**Issue by z0rc** [so-fancy/diff-so-fancy#182] opened 2016-07-13 10:24 UTC
I'm on OS X and have file with `\r\n` line endings:

``` sh
$ file logstash-autoscale-group.template
logstash-autoscale-group.template: ASCII English text, with CRLF line terminators
```

When checking `git diff` for changes in this file (with diff-so-fancy), the `^M` symbol appears at the end of _some_ lines (colors omitted):

```
...
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: aws_cf_templates/logstash-autoscale-group.template
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ logstash-autoscale-group.template:93 @
      "Type" : "String",
      "Default": "hipchat-ops"
    },
    "LambdaCodeFileName": {^M
      "Description": "File in Assets bucket containing Lambda code",^M
    "LambdaR53UpsertCodeFileName": {^M
      "Description": "File in Assets bucket containing Lambda code of Route53 update",^M
      "Type": "String",
      "Default": "lambda/asg-sns-update-route53.zip"
    },
    "LambdaCodeHandler": {^M
      "Description": "Lambda code main handler",^M
    "LambdaR53UpsertCodeHandler": {^M
      "Description": "Route53 update Lambda code main handler",^M
      "Type": "String",
      "Default": "index.handler"
    },
    "LambdaS3ToSQSCodeFileName": {
      "Description": "File in Assets bucket containing Lambda code of S3 to SQS publisher",
      "Type": "String",
      "Default": "lambda/s3-to-sqs-publisher.zip"
    },
    "LambdaS3ToSQSCodeHandler": {
      "Description": "S3 to SQS publisher Lambda code main handler",
      "Type": "String",
      "Default": "publisher.lambda_handler"
    },
    "TagName": {
      "Description": "Tag: Name",
      "Type": "String",
...
```

I checked output of `report-bug.sh` for this diff and it shows that `^M` is present at then end of each line from file.

I believe this `^M` should be `chop`ed from stdout always.

**Comment by scottchiefbaker** [comment] 2016-07-13 15:45
I can recreate this... I wonder if this is a `less` thing, making the `\r` visible?

It's an easy fix, but I think we should get a consensus before we make this change. Thoughts: @stevemao @paulirish @noscript @OJFord

**Comment by noscript** [comment] 2016-07-13 17:42
`^M` appears if the line endings were changed. I think this is valuable and should be kept.

**Comment by OJFord** [comment] 2016-07-13 18:26
Then perhaps, if the terminal supports unicode, there could be a - *ahem* - fancier (clearer intent)  character to indicate changed line endings? Some sort of vertical squiggle maybe.

**Comment by scottchiefbaker** [comment] 2016-07-13 18:28
I created a file like the following:

```
echo -e "Hello there, how are you?\r\n" > test.txt
echo -e "Hello there, how are you?\r\n" >> test.txt
echo -e "Hello there, how are you?\r\n" >> test.txt
```

I committed that file, and then changed `there` to `three` (no change to the line endings) and the `^M` showed up at the end. I don't think it ONLY shows if the line endings were changed. Maybe I'm wrong though.

**Comment by OJFord** [comment] 2016-07-13 18:30
@scottchiefbaker How did you change `there` to `three` though?

I wouldn't be sure of how to do that and guarantee that _something_ wasn't changing the line endings. `sed`, I suppose.

**Comment by scottchiefbaker** [comment] 2016-07-13 18:55
@OJFord just using Vim... Vim will **not** change line endings for no reason.

**Comment by OJFord** [comment] 2016-07-14 07:05
@scottchiefbaker Perhaps I'm misunderstanding, but:

> Suppose your system has ffs=dos,unix and you open an existing file. Vim will look for both dos and unix line endings, but Vim has a built-in preference for the unix format.
>
>If all lines in the file end with CRLF, the dos file format will be applied, meaning that each CRLF is removed when reading the lines into a buffer, and the buffer 'ff' option will be dos.
If one or more lines end with LF only, the unix file format will be applied, meaning that each LF is removed (but each CR will be present in the buffer, and will display as ^M), and the buffer 'ff' option will be unix.
http://vim.wikia.com/wiki/File_format

**Comment by z0rc** [comment] 2016-07-14 08:15
Let me clarify a bit. This ticket has nothing to with Vim and how it handles line endings. Here is screenshot with colors, so it would make more sense.
![screen shot 2016-07-14 at 11 09 14](https://cloud.githubusercontent.com/assets/787519/16832592/938a9300-49b3-11e6-8dfe-eb66f87b00df.png)
I'm confident, that this change didn't touch line endings and all lines in file still end with CRLF.

**Comment by scottchiefbaker** [comment] 2017-02-23 17:13
Ok I think I've created steps to recreate this on my Linux box. Can someone else verify: 

```
echo SGVsbG8gU2NvdHQsIGhvdyBhcmUgeW91Pw0KCkhlbGxvIHRoZXJlLCBob3cgYXJlIHlvdT8NCgo= | base64 -d > test.txt
git commit -a -m "One"

perl -pi -e 's/Scott/Sammy/' test.txt
git diff
```

will generate the above mentioned bug?

**Comment by OJFord** [comment] 2017-02-24 03:00
Yep, that reproduces it for me; on mac.

**Comment by monoblaine** [comment] 2017-05-29 22:08
I had the same issue and used this super-simple-and-stupid fix:

https://github.com/monoblaine/diff-so-fancy/commit/49e7c9a5fb79fce314e21dbd614b4d94e8d18dab

I can create a PR if it's not as stupid as I think.

**Comment by scottchiefbaker** [comment] 2017-05-30 15:20
@monoblaine I'll do some testing on your fix. It looks like all you're doing is an ANSI reset? Any idea WHY that works?

**Comment by monoblaine** [comment] 2017-05-30 18:38
@scottchiefbaker At first, I just added the following line (Remove the carriage return from the end of the line):

```perl
$line =~ s/\r\n$/\n/;
```

The other line, however, seems weird to me, too:

```perl
$line =~ s/($ansi_color_regex)\r$reset_color_regex_pattern//;
```

It looks as if there was some text like the following that I wanted to have removed:

```
[SOME_ANSI_COLOR]^M[ANSI_COLOR_RESET]
```

But I wasn't able to reproduce it.

**Comment by scottchiefbaker** [comment] 2017-05-30 18:55
I don't think we can blindly remove `\r` at the end of a line. There are valid cases where you change `\r\n` in your commit and you want to be able to see that in the diff.

**Comment by scottchiefbaker** [comment] 2019-01-17 22:18
I'm going to close this as a `WONTFIX` for now because I think there are valid cases where you WANT to see the `^M` at the end. 

For example if you change ALL the line endings on a file from `\r\n` to `\n` there is no way for d-s-f to show that other than what diff already does with the `^M`. 

If we can come up with another use case, or valid example I'm fine to re-open this issue.

**Closed by scottchiefbaker** 2019-01-17 22:18 UTC
Labels: bug

**Comment by francescoferraioli** [comment] 2022-03-01 05:39
It would be nice to have an option for `diff-so-fancy` to hide the ^M character from the diff. I understand it shouldn't be the default but I think it would be nice to be able to configure it to do so.
