### ISSUE TITLE
`my $VERSION = "1.4.2";` in 1.4.3 version bump

### ISSUE THREAD

**Issue by rlue** [so-fancy/diff-so-fancy#418] opened 2021-07-29 13:39 UTC
Namely, a673cb4

**Comment by rlue** [comment] 2021-07-29 13:41
(To clarify, I mean to say that line 3 of the `diff-so-fancy` script was not updated in this commit, not that any change in this commit was erroneous.)

**Comment by scottchiefbaker** [comment] 2022-04-07 14:09
I (@scottchiefbaker) maintain the Perl code and handle the GitHub releases. Other people work on the `npm` versions and specific packages versions. Looks like in this case there was a minor discrepancy in the cycle.

@paulirish am I correct in my understanding that the `package.json` file is an `npm` thing? Personally I never touch that file, so I just assume it's for something you do?

**Comment by barryprice** [comment] 2023-02-15 07:18
I think the issue is that the version in package.json was updated if you check out the v1.4.3 tag, but that the $VERSION variable in the script itself is not:

1.4.3: https://github.com/so-fancy/diff-so-fancy/blob/v1.4.3/package.json

1.4.3: https://github.com/so-fancy/diff-so-fancy/blob/v1.4.3/package-lock.json

1.4.2: https://github.com/so-fancy/diff-so-fancy/blob/v1.4.3/diff-so-fancy

1.4.2: https://github.com/so-fancy/diff-so-fancy/blob/v1.4.3/third_party/build_fatpack/diff-so-fancy

**Comment by scottchiefbaker** [comment] 2023-06-09 17:42
Closing for now, as this is an issue in a past release and we are just about to release a new version which should NOT have this issue.

**Closed by scottchiefbaker** 2023-06-09 17:42 UTC
